Review code of dnldd
raedahgroup/dcrtxmatcher pull request #36
Opened 2018-11-02 04:00 UTC by huyntsgs

1. The if-else here https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L43, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L82 would be more readable
broken into two if statements with comments explaining what constitutes a blind server and a 
normal server.

2. uneeded newlines here https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L55, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L71, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L32, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/service.go#L33,
https://github.com/raedahgroup/dcrtxmatcher/blob/master/service.go#L77

3. You have this snippet handling repeated quite a bit:
	if done(ctx) {
		return ctx.Err()
	}

here: https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L101-L103, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L39-L41, 
https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L109-L111

better off using a non blocking receive for the context in a loop, after starting
the server's listen and serve goroutine.

out:
	for {
			select {
			case <-ctx.Done():
				break out
			default:
				// Non-blocking receive fallthrough.
			}
	}

4. Unsure what you need this for: https://github.com/raedahgroup/dcrtxmatcher/blob/master/dcrtxmatcher.go#L139
do elaborate.

5. The grammar of comments need improvement, please refer to dicemix's review and update accordingly.

6. I think FindMatches can be simplified, does AddParticipant really need a goroutine? https://github.com/raedahgroup/dcrtxmatcher/blob/master/service.go#L32

7. I get the pattern you're going for with SplitTxMatcherService methods, you want the cancellation signal to terminate every executing process when given. Still giving it a thought, 
you might be overdoing it I'm not entirely sure yet, will get back to you on this.
*Update*, discussed this with Dave:
```
If you cancel the context after the long running queue join has began, the code will leak the goroutine
The goroutine will be blocked on sending to the done channel which nothing is listening for anymore because it was cancelled
Need to buffer it So that when the cancel happens, the sending gr will still send the data into the buffered channel and then it will go out of scope and get garbage collected.

Also, it looks `peer, _ := peer.FromContext(ctx)` is a *gross* misuse of context
https://medium.com/@cep21/how-to-correctly-use-context-context-in-go-1-7-8f2c0fafdf39
And storing the peer in the context is horrible `Context.Value should inform, not control`
That `peer, _ := peer.FromContext(ctx)` is clearly storing the peer in the `Value` and using it to `control`.
```The content of context.Value is for maintainers not users. It should never be required input for documented or expected results.```
```

2018-11-02 04:02 UTC, huyntsgs commented
This is my feedback.
1. Updated and added more comments.

2. Removed.

3. I do not see much issue with this code.
	if done(ctx) {
		return ctx.Err()
	}

You can see similar codes in dcrwallet: https://github.com/raedahgroup/dcrwallet/blob/master/dcrwallet.go#L143-L145
https://github.com/raedahgroup/dcrwallet/blob/master/dcrwallet.go#L256-L258
https://github.com/raedahgroup/dcrwallet/blob/master/dcrwallet.go#L204-L206

4. The code is for checking whether context is cancelled or not as https://github.com/raedahgroup/dcrwallet/blob/master/dcrwallet.go#L61-L68

5. I have rechecked and updated.

6. AddParticipant needs goroutine because it is long running process and we want it not blocking the cancel context.

7. I have fixed issue with done channel. 

And about `peer, _ := peer.FromContext(ctx)`. You may misunderstand the peer.FromContext(ctx) here. I do not save any data into peer.

This is grpc storing. And it is only the ip address. Also, I find this is only method for getting client ip address in grpc.

https://github.com/grpc/grpc-go/issues/2259
https://stackoverflow.com/questions/51753461/how-can-i-get-the-client-ip-address-and-user-agent-in-golang-grpc

2018-11-12 23:50 UTC, dnldd requested changes

2018-11-12 23:50 UTC, dnldd commented on dcrtxmatcher.go
> +	// With normal coin join method, server known output address of all participants.
... the server knows the output addresses of all participants.

2018-11-12 23:50 UTC, dnldd commented on matcher/matcher.go
> +// CheckInputsSigned returns true if all participants already sent their signed transaction input, output.
...signed transaction inputs.

2018-11-12 23:50 UTC, dnldd commented on matcher/matcher.go
> +// mergeSignedInput merges signed transaction data of each participant to one.
... merges all signed transaction data from each participant.

2018-11-12 23:50 UTC, dnldd commented on matcher/matcher.go
> +			// Check participants who not sending data and remove.
The updates to the comments made are better but still not there yet, grammar is still a problem. I've pointed out a couple of cases here. Take another look and correct.

2018-11-12 23:50 UTC, dnldd commented on matcher/matcher.go
> +	// If RandomIndex option is enable, server swaps randomly both input and output index.
... is enabled, input and output indices are randomly swapped.

2018-11-12 23:51 UTC, dnldd requested changes
The updates to the comments made are better but still not there yet, grammar is still a problem. I've pointed out a couple of cases here. Take another look and correct.

2018-11-12 23:54 UTC, dnldd commented
`Context.Value should inform, not control` still stands here for `peer, _ := peer.FromContext(ctx)`. (refer to https://medium.com/@cep21/how-to-correctly-use-context-context-in-go-1-7-8f2c0fafdf39).

2018-12-02 02:40 UTC, closed without merging